[[constraint]]
  name = "github.com/pkg/errors"
  version = "v0.9.1"

[[constraint]]
  name = "github.com/go-ozzo/ozzo-validation"
  version = "v4.1.0"

[[constraint]]
  name = "github.com/go-yaml/yaml"
  version = "v2.2.8"

[[constraint]]
  name = "github.com/joho/godotenv"
  version = "1.3.0"

[[constraint]]
  name = "github.com/samuel/go-zookeeper"
  branch = "master"

[prune]
  go-tests = true
  unused-packages = true
